options(repos = BiocManager::repositories())
if (!require("devtools")) install.packages("devtools", repos="http://cran.us.r-project.org")
if (!require("shiny")) install.packages("shiny", repos="http://cran.us.r-project.org")
if (!require("servr")) install.packages("servr", repos="http://cran.us.r-project.org")
if (!require("ggplot2")) install.packages("ggplot2", repos="http://cran.us.r-project.org")
if (!require("pheatmap")) install.packages("pheatmap", repos="http://cran.us.r-project.org")
if (!require("plotly")) install.packages("plotly", repos="http://cran.us.r-project.org")
if (!require("shinyjs")) install.packages("shinyjs", repos="http://cran.us.r-project.org")
if (!require("DT")) install.packages("DT", repos="http://cran.us.r-project.org")
if (!require("dplyr")) install.packages("dplyr", repos="http://cran.us.r-project.org")
if (!require("pbmcapply")) install.packages("pbmcapply", repos="http://cran.us.r-project.org")
if (!require("reshape2")) install.packages("reshape2", repos="http://cran.us.r-project.org")
if (!require("shinydashboard")) install.packages("shinydashboard", repos="http://cran.us.r-project.org")
if (!require("shinyalert")) install.packages("shinyalert", repos="http://cran.us.r-project.org")
if (!require("shinyFiles")) install.packages("shinyFiles", repos="http://cran.us.r-project.org")
if (!require("shinyWidgets")) install.packages("shinyWidgets", repos="http://cran.us.r-project.org")
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if (!require("M3C")) BiocManager::install("M3C")
if (!require("RUVSeq")) BiocManager::install("RUVSeq")
if (!require("scales")) install.packages("scales", repos="http://cran.us.r-project.org")
if (!require("dtwclust")) install.packages("dtwclust", repos="http://cran.us.r-project.org")
if (!require("dplyr")) install.packages("dplyr", repos="http://cran.us.r-project.org")
if (!require("DESeq2")) BiocManager::install("DESeq2")
if (!require("ggcorrplot")) install.packages("ggcorrplot", repos="http://cran.us.r-project.org")
if (!require("tibble")) install.packages("tibble", repos="http://cran.us.r-project.org")
if (!require("ReactomePA")) BiocManager::install("ReactomePA")
if (!require("org.Hs.eg.db")) BiocManager::install("org.Hs.eg.db")
if (!require("org.Mm.eg.db")) BiocManager::install("org.Mm.eg.db")
if (!require("AnnotationDbi")) BiocManager::install("AnnotationDbi")
if (!require("ChIPseeker")) BiocManager::install("ChIPseeker")
if (!require("TxDb.Hsapiens.UCSC.hg19.knownGene")) BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene")
if (!require("TxDb.Mmusculus.UCSC.mm10.knownGene")) BiocManager::install("TxDb.Mmusculus.UCSC.mm10.knownGene")
if (!require("TxDb.Hsapiens.UCSC.hg38.knownGene")) BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")
if (!require("TxDb.Mmusculus.UCSC.mm9.knownGene")) BiocManager::install("TxDb.Mmusculus.UCSC.mm9.knownGene")
if (!require("clusterProfiler")) BiocManager::install("clusterProfiler")
if (!require("cowplot")) install.packages("cowplot", repos="http://cran.us.r-project.org")
if (!require("scater")) BiocManager::install("scater")
if (!require("hdf5r")) install.packages("hdf5r", repos="http://cran.us.r-project.org")
if (!require("MAST")) BiocManager::install("MAST")
if (!require("Seurat")) install.packages("Seurat", repos="http://cran.us.r-project.org")
